# Generated by Django 3.2.19 on 2025-01-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
